version: '3.8'
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: rentalradar
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  rental-radar-web:
    image: rental-radar-web:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"